### ISSUE TITLE
Error creating new layer (on edition session) after Geoportal version upgrade

### ISSUE THREAD

**Issue by cayetanobv** [GeographicaGS/Alboran#17]
Error creating new WMS layer (third party, not ctreating on Geoserver). It could be a permissions issue... (write access in DB?).

Screenshot:
![image](https://cloud.githubusercontent.com/assets/7315379/16136171/b4498178-3428-11e6-857f-3eb56737ec53.png)

**Comment by neokore** [comment]
Solved. The problem was the sequence that was not adjusted to continue with the last id.

**Comment by cayetanobv** [comment]
I checked this error and it is fixed. I'm going to close issue.
