### ISSUE TITLE
Catálogo - sistema de filtros

### ISSUE THREAD

**Issue by cayetanobv** [GeographicaGS/Alboran#27]
Filtros por subbloque y fuente. Añadir el sistema de tags de documentación, aunque no funcione por no existir ningún registro con tags en la BBDD todavía.

![Uploading 02_alboran_catalogo.jpg…]()

**Comment by josegilg** [comment]
He actualizado el PSD incluyendo el desplegable de Fuente e incorporando los Tags (que lo he reajustado). Esto aplicaría también a la sección de documentación.
