### ISSUE TITLE
elegir imágenes para nuevas secciones

### ISSUE THREAD

**Issue by cayetanobv** [GeographicaGS/Alboran#31]
Ya están en Drive en Alboran/operaciones/fotos

**Comment by cayetanobv** [comment]
@padawannn en cuanto @josegilg decida fotos, se cambian dónde están provisionales

**Comment by josegilg** [comment]
He dejado imágenes para utilizar de fondo: recortadas para que el centro tenga sentido y pasadas a b/n.

**Comment by cayetanobv** [comment]
@padawannn si todo está Ok y no falta ninguna, cerramos

**Comment by cayetanobv** [comment]
@josegilg revisa que las imágenes se han encajado tal y cómo habías previsto. Pega un vistazo al resto de cosas y nos dices si hay algo.
