### ISSUE TITLE
Actualizar imágenes sección "Cómo usarlo"

### ISSUE THREAD

**Issue by cayetanobv** [GeographicaGS/Alboran#36]
Adaptar imágenes a nueva web:
http://www.iucn-geoportalboran.org/es/comousarlo

**Comment by josegilg** [comment]
No puedo etiquetar:  in progress

**Comment by cayetanobv** [comment]
@padawannn cuando @josegilg acabe cierras tú esta tarea subiendo las imágenes nuevas.

**Comment by josegilg** [comment]
@padawannn ya las tienes.

**Comment by padawannn** [comment]
Listo
