### ISSUE TITLE
Cambiar pines por el diseño final

### ISSUE THREAD

**Issue by javigil-geo** [GeographicaGS/Alboran#45]
![captura de pantalla 2016-10-13 a las 16 32 01](https://cloud.githubusercontent.com/assets/19855697/19353135/a2b435e2-9162-11e6-9d33-584b768c6be8.png)

![captura de pantalla 2016-10-13 a las 16 33 59](https://cloud.githubusercontent.com/assets/19855697/19353216/e0acb2b6-9162-11e6-876e-a90685833d24.png)

**Comment by padawannn** [comment]
@javigil-geo cuando me paséis los iconos a tamaño correcto lo meto

**Comment by javigil-geo** [comment]
https://drive.google.com/open?id=0B0UH4LXpUE0YTFZRajJwdnJGdzg
