### ISSUE TITLE
Actualización y corrección de estilos del catálogo

### ISSUE THREAD

**Issue by javigil-geo** [GeographicaGS/Alboran#48]
![captura de pantalla 2016-10-13 a las 16 46 47](https://cloud.githubusercontent.com/assets/19855697/19353793/ccbf685a-9164-11e6-8822-460b14eabed7.png)

Correcto:
![captura de pantalla 2016-10-13 a las 16 46 39](https://cloud.githubusercontent.com/assets/19855697/19353797/d1faa780-9164-11e6-9be9-a1814234537c.png)

**Comment by javigil-geo** [comment]
![captura de pantalla 2016-10-13 a las 16 49 01](https://cloud.githubusercontent.com/assets/19855697/19353835/fa157614-9164-11e6-86af-14f0a4679b6a.png)

**Correcto:**
![captura de pantalla 2016-10-13 a las 16 46 39](https://cloud.githubusercontent.com/assets/19855697/19353842/fdda83f2-9164-11e6-8875-8ed205875234.png)

**Comment by javigil-geo** [comment]
Corregir espacios:
![captura de pantalla 2016-10-13 a las 16 50 16](https://cloud.githubusercontent.com/assets/19855697/19353905/2b5dc410-9165-11e6-8de9-d9e1641e86c0.png)
![captura de pantalla 2016-10-13 a las 16 50 03](https://cloud.githubusercontent.com/assets/19855697/19353906/2b6187ee-9165-11e6-81e0-49cc5ea0fdbd.png)

**Comment by javigil-geo** [comment]
Los botones deben de ir en los colores de la sección:
![captura de pantalla 2016-10-13 a las 16 51 32](https://cloud.githubusercontent.com/assets/19855697/19353947/51ff5f02-9165-11e6-9f93-9342c868c42b.png)

**Comment by cayetanobv** [comment]
El primero no está hecho.
