### ISSUE TITLE
Actualizaciones menores en "El proyecto" - textos + logos + tipografía

### ISSUE THREAD

**Issue by cayetanobv** [GeographicaGS/Alboran#50]
Varias pequeñas tareas:

-  [x] Tarea 1:
![image](https://cloud.githubusercontent.com/assets/7315379/20622930/6c608224-b305-11e6-9707-a95002806c92.png)

-  [x] Tarea 2:
![image](https://cloud.githubusercontent.com/assets/7315379/20623078/371a7380-b306-11e6-81ca-fc2a28b70037.png)

-  [x] Tarea 3:
![image](https://cloud.githubusercontent.com/assets/7315379/20622998/beb72474-b305-11e6-8b18-fb11bda7d9b3.png)

-  [x] Tarea 4:
![image](https://cloud.githubusercontent.com/assets/7315379/20623117/6bfaf0e8-b306-11e6-8b3b-09d33446edbb.png)

- [x] Tarea 5:
![image](https://cloud.githubusercontent.com/assets/7315379/20623163/9aaf8c46-b306-11e6-9c79-39a424dc260a.png)

- [x] Tarea 6:
![image](https://cloud.githubusercontent.com/assets/7315379/20623316/4b2cfa4a-b307-11e6-8685-6ae0a0b21f15.png)

**Comment by javigil-geo** [comment]
Actualizado el esquema de la Tarea 4:
https://drive.google.com/open?id=0B_QGNYzQG9_DclM5TVhuVGFnMnM
